run:
  timeout: 5m

linters-settings:
  misspell:
    locale: US
  staticcheck:
    checks: ["all", "-SA6002"]
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: error-strings
        disabled: true

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - gocritic
    - gomodguard
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused

issues:
  exclude-use-default: false
  exclude-rules:
    - text: "don't use ALL_CAPS in Go names"
      linters:
        - revive
