linters-settings:
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - revive
    - ineffassign
    - gosimple
    - unused
    - prealloc
    - unconvert
    - gofumpt

issues:
  exclude-use-default: false
  exclude:
      - should have a package comment
      - error strings should not be capitalized or end with punctuation or a newline
      - don't use ALL_CAPS in Go names
service:
  golangci-lint-version: 1.51.0 # use the fixed version to not introduce new linters unexpectedly
