linters-settings:
  golint:
    min-confidence: 0

  misspell:
    locale: US

  staticcheck:
    checks: ['all', '-SA6002']
    
linters:
  disable-all: true
  enable:
    - durationcheck
    - gocritic
    - gofumpt
    - goimports
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused

issues:
  exclude-use-default: false
  exclude:
      - should have a package comment
      - error strings should not be capitalized or end with punctuation or a newline
      - don't use ALL_CAPS in Go names
